using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

namespace WindowsFormsApp1
{
    class DB  //Test databank of component compatibilities
    {
        public static List<string> Alcoholic = new List<string> {"Vodka","Coffee liqueur","Prosecco","Brandy","Cognac","Champagne","Whiskey","Sherry","Gin",
                "Rum","Triple Sec","Lillet Vermouth","Cachaça","Pusser’s Navy Rum","Dry Vermouth","Sweet Vermouth","Sparkling Wine","Italian Vermouth",
                "Fernet-Branca","Campari","Cointreau","Combier","Tequila","Mezcal","Benedictine","Maraschino Liqueur","White Rum","Amaretto","Pisco",
                "Vermouth","Rye Whiskey","Amaro","Gosling’s Rum","Ginger Beer","Lillet Blanc","Absinthe","Scotch","Smoky Islay Scotch","Aperol",
                "Orange liqueur","Dry Martini","Spicy Rye"};
        public static List<string> Nonalcoholic = new List<string> {"Coca Cola","Soda","Pineapple juice","Orange juice","Syrup","Lemon juice","Lime juice","Orange flower water",
                "Cranberry juice","Raspberry syrup","Ginger Syrup","Tomato juice","Demerara syrup","Milk","Red-bull"};
        public static List<string> NonDrink = new List<string> {"Lemon", "Lime","Egg", "Orange", "Ice", "Sugar", "Angostura bitters", "Mint", "Maraschino Cherries",
                "Orange bitters","Peach puree","Cream","Heavy cream","Half and Half","Honey","Egg White","Grapefruit","Spindrift grapefruit","Peychauds bitters",
                "Creme de Violette","Creme Yvette","Sweetener","Spices","Cane Sugar","Muddled mint","Coconut cream"};
        public static Dictionary<string, List<string>> Compatibility = new Dictionary<string, List<string>>() {
                { "VodkaPos", new List<string> {"Coca Cola","Heavy cream","Half and half","Coffee liqueur",
                    "Cranberry juice","Lime juice","Tomato juice","Spices","Lime","Soda","Orange juice","Syrup","Cranberry juice","Raspberry syrup",
                    "Red-bull","Lemon","Orange","Sugar","Spices","Orange liqueur","Lemon juice","Ginger Syrup","Ice","Cane Sugar"}},
                { "VodkaNeu", new List<string> {"Gin","Triple Sec","Campari","Maraschino Liqueur","Raki","Pineapple juice","Orange flower water","Demerara syrup",
                    "Egg","Maraschino Cherries","Grapefruit","Spindrift grapefruit","Sweetener"}},
                { "VodkaNeg", new List<string> { "Milk", "Prosecco","Brandy","Cognac","Champagne","Whiskey","Sherry","Tequila","Rum","Cachaça","Pusser’s Navy Rum",
                    "Sparkling Wine","Gin","Dry Vermouth","Sweet Vermouth","Italian Vermouth","Cointreau","Combier","Mezcal","Benedictine","White Rum","Amaretto",
                    "Pisco","Vermouth","Rye Whiskey","Amaro","Gosling’s Rum","Ginger Beer","Absinthe","Scotch","Smoky Islay Scotch","Dry Martini","Spicy Rye",
                    "Coconut cream","Mint","Angostura Bitters","Orange bitters","Peach puree","Cream","Heavy cream","Half and Half","Honey","Egg White",
                    "Peychauds bitters","Creme de Violette","Creme Yvette","Muddled mint"}},
                { "Coffee liqueurPos", new List<string> {"Coca Cola","Vodka","Whiskey","Gin","Tequila","Rum","Pusser’s Navy Rum","White Rum","Amaretto","Rye Whiskey","Amaro",
                    "Gosling’s Rum","Scotch","Smoky Islay Scotch","Spicy Rye","Raki","Lemon","Lime","Ice","Cream","Heavy cream","Half and Half"} },
                { "Coffee liqueurNeu", new List<string> {"Brandy","Cognac","Sherry","Cointreau","Mezcal","Benedictine","Pisco","Syrup","Milk","Orange","Sugar",
                    "Honey","Grapefruit","Spindrift grapefruit","Creme de Violette","Creme Yvette","Sweetener","Cane Sugar"}},
                { "Coffee liqueurNeg", new List<string> {"Prosecco","Champagne","Triple Sec","Lillet Vermouth","Cachaça","Dry Vermouth","Sweet Vermouth","Sparkling Wine",
                    "Italian Vermouth","Fernet-Branca","Campari","Combier","Maraschino Liqueur","Vermouth","Ginger Beer","Absinthe","Orange liqueur","Dry Martini",
                    "Soda","Coconut cream","Pineapple juice","Orange juice","Lemon juice","Lime juice","Orange flower water","Cranberry juice","Raspberry syrup",
                    "Ginger Syrup","Tomato juice","Demerara syrup","Egg","Mint","Angostura Bitters","Maraschino Cherries","Orange bitters","Peach puree","Egg White",
                    "Peychauds bitters","Spices","Muddled mint"}},

                { "Angostura bittersPos", new List<string> {""}},
                { "Angostura bittersNeu", new List<string> {""}},
                { "Angostura bittersNeg", new List<string> {""}},

                { "MintPos", new List<string> {""}},
                { "MintNeu", new List<string> {""}},
                { "MintNeg", new List<string> {""}},

                { "Maraschino CherriesPos", new List<string> {""}},
                { "Maraschino CherriesNeu", new List<string> {""}},
                { "Maraschino CherriesNeg", new List<string> {""}},

                { "Orange bittersPos", new List<string> {""}},
                { "Orange bittersNeu", new List<string> {""}},
                { "Orange bittersNeg", new List<string> {""}},

                { "Peach pureePos", new List<string> {""}},
                { "Peach pureeNeu", new List<string> {""}},
                { "Peach pureeNeg", new List<string> {""}},

                { "CreamPos", new List<string> {""}},
                { "CreamNeu", new List<string> {""}},
                { "CreamNeg", new List<string> {""}},

                { "Heavy creamPos", new List<string> {""}},
                { "Heavy creamNeu", new List<string> {""}},
                { "Heavy creamNeg", new List<string> {""}},

                { "Half and HalfPos", new List<string> {""}},
                { "Half and HalfNeu", new List<string> {""}},
                { "Half and HalfNeg", new List<string> {""}},

                { "HoneyPos", new List<string> {""}},
                { "HoneyNeu", new List<string> {""}},
                { "HoneyNeg", new List<string> {""}},

                { "Egg WhitePos", new List<string> {""}},
                { "Egg WhiteNeu", new List<string> {""}},
                { "Egg WhiteNeg", new List<string> {""}},

                { "GrapefruitPos", new List<string> {""}},
                { "GrapefruitNeu", new List<string> {""}},
                { "GrapefruitNeg", new List<string> {""}},

                { "Spindrift grapefruitPos", new List<string> {""}},
                { "Spindrift grapefruitNeu", new List<string> {""}},
                { "Spindrift grapefruitNeg", new List<string> {""}},

                { "Peychauds bittersPos", new List<string> {""}},
                { "Peychauds bittersNeu", new List<string> {""}},
                { "Peychauds bittersNeg", new List<string> {""}},

                { "Creme de ViolettePos", new List<string> {""}},
                { "Creme de VioletteNeu", new List<string> {""}},
                { "Creme de VioletteNeg", new List<string> {""}},

                { "Creme YvettePos", new List<string> {""}},
                { "Creme YvetteNeu", new List<string> {""}},
                { "Creme YvetteNeg", new List<string> {""}},

                { "SweetenerPos", new List<string> {""}},
                { "SweetenerNeu", new List<string> {""}},
                { "SweetenerNeg", new List<string> {""}},

                { "SpicesPos", new List<string> {""}},
                { "SpicesNeu", new List<string> {""}},
                { "SpicesNeg", new List<string> {""}},

                { "Cane SugarPos", new List<string> {""}},
                { "Cane SugarNeu", new List<string> {""}},
                { "Cane SugarNeg", new List<string> {""}},

                { "Muddled mintPos", new List<string> {""}},
                { "Muddled mintNeu", new List<string> {""}},
                { "Muddled mintNeg", new List<string> {""}},

                { "Coconut creamPos", new List<string> {""}},
                { "Coconut creamNeu", new List<string> {""}},
                { "Coconut creamNeg", new List<string> {""}},

                { "White RussianPos", new List<string> { "" }},
                { "White RussianNeu", new List<string> { "" }},
                { "White RussianNeg", new List<string> { "" }},

                { "Black RussianPos", new List<string> { "" }},
                { "Black RussianNeu", new List<string> { "" }},
                { "Black RussianNeg", new List<string> { "" }},

                { "BelliniPos", new List<string> { "" }},
                { "BelliniNeu", new List<string> { "" }},
                { "BelliniNeg", new List<string> { "" }},

                { "Champagne CocktailPos", new List<string> { "" }},
                { "Champagne CocktailNeu", new List<string> { "" }},
                { "Champagne CocktailNeg", new List<string> { "" }},

                { "Irish CoffeePos", new List<string> { "" }},
                { "Irish CoffeeNeu", new List<string> { "" }},
                { "Irish CoffeeNeg", new List<string> { "" }},

                { "BambooPos", new List<string> { "" }},
                { "BambooNeu", new List<string> { "" }},
                { "BambooNeg", new List<string> { "" }},

                { "Long Island Iced TeaPos", new List<string> { "" }},
                { "Long Island Iced TeaNeu", new List<string> { "" }},
                { "Long Island Iced TeaNeg", new List<string> { "" }},

                { "VesperPos", new List<string> { "" }},
                { "VesperNeu", new List<string> { "" }},
                { "VesperNeg", new List<string> { "" }},

                { "CaipirinhaPos", new List<string> { "" }},
                { "CaipirinhaNeu", new List<string> { "" }},
                { "CaipirinhaNeg", new List<string> { "" }},

                { "Tom CollinsPos", new List<string> { "" }},
                { "Tom CollinsNeu", new List<string> { "" }},
                { "Tom CollinsNeg", new List<string> { "" }},

                { "PainkillerPos", new List<string> { "" }},
                { "PainkillerNeu", new List<string> { "" }},
                { "PainkillerNeg", new List<string> { "" }},

                { "Bees KneesPos", new List<string> { "" }},
                { "Bees KneesNeu", new List<string> { "" }},
                { "Bees KneesNeg", new List<string> { "" }},

                { "Ramos Gin FizzPos", new List<string> { "" }},
                { "Ramos Gin Fizz", new List<string> { "" }},
                { "Ramos Gin FizzNeg", new List<string> { "" }},

                { "BramblePos", new List<string> { "" }},
                { "BrambleNeu", new List<string> { "" }},
                { "BrambleNeg", new List<string> { "" }},

                { "Vodka MartiniPos", new List<string> { "" }},
                { "Vodka MartiniNeu", new List<string> { "" }},
                { "Vodka MartiniNeg", new List<string> { "" }},

                { "Hanky PankyPos", new List<string> { "" }},
                { "Hanky PankyNeu", new List<string> { "" }},
                { "Hanky PankyNeg", new List<string> { "" }},

                { "Jungle BirdPos", new List<string> { "" }},
                { "Jungle BirdNeu", new List<string> { "" }},
                { "Jungle BirdNeg", new List<string> { "" }},

                { "White LadyPos", new List<string> { "" }},
                { "White LadyNeu", new List<string> { "" }},
                { "White LadyNeg", new List<string> { "" }},

                { "PalomaPos", new List<string> { "" }},
                { "PalomaNeu", new List<string> { "" }},
                { "PalomaNeg", new List<string> { "" }},

                { "CosmopolitanPos", new List<string> { "" }},
                { "CosmopolitanNeu", new List<string> { "" }},
                { "CosmopolitanNeg", new List<string> { "" }},

                { "SidecarPos", new List<string> { "" }},
                { "SidecarNeu", new List<string> { "" }},
                { "SidecarNeg", new List<string> { "" }},

                { "French 75Pos", new List<string> { "" }},
                { "French 75Neu", new List<string> { "" }},
                { "French 75Neg", new List<string> { "" }},

                { "Vieux CarréPos", new List<string> { "" }},
                { "Vieux CarréNeu", new List<string> { "" }},
                { "Vieux CarréNeg", new List<string> { "" }},

                { "AviationPos", new List<string> { "" }},
                { "AviationNeu", new List<string> { "" }},
                { "AviationNeg", new List<string> { "" }},

                { "Piña ColadaPos", new List<string> { "" }},
                { "Piña ColadaNeu", new List<string> { "" }},
                { "Piña ColadaNeg", new List<string> { "" }},

                { "Amaretto SourPos", new List<string> { "" }},
                { "Amaretto SourNeu", new List<string> { "" }},
                { "Amaretto SourNeg", new List<string> { "" }},

                { "Pisco SourPos", new List<string> { "" }},
                { "Pisco SourNeu", new List<string> { "" }},
                { "Pisco SourNeg", new List<string> { "" }},

                { "AmericanoPos", new List<string> { "" }},
                { "AmericanoNeu", new List<string> { "" }},
                { "AmericanoNeg", new List<string> { "" }},

                { "GimletPos", new List<string> { "" }},
                { "GimletNeu", new List<string> { "" }},
                { "GimletNeg", new List<string> { "" }},

                { "Mai TaiPos", new List<string> { "" }},
                { "Mai TaiNeu", new List<string> { "" }},
                { "Mai TaiNeg", new List<string> { "" }},

                { "BoulevardierPos", new List<string> { "" }},
                { "BoulevardierNeu", new List<string> { "" }},
                { "BoulevardierNeg", new List<string> { "" }},

                { "Clover ClubPos", new List<string> { "" }},
                { "Clover ClubNeu", new List<string> { "" }},
                { "Clover ClubNeg", new List<string> { "" }},

                { "Gin FizzPos", new List<string> { "" }},
                { "Gin FizzNeu", new List<string> { "" }},
                { "Gin FizzNeg", new List<string> { "" }},

                { "Dark ’N’ StormyPos", new List<string> { "" }},
                { "Dark ’N’ StormyNeu", new List<string> { "" }},
                { "Dark ’N’ StormyNeg", new List<string> { "" }},

                { "Corpse ReviverPos", new List<string> { "" }},
                { "Corpse ReviverNeu", new List<string> { "" }},
                { "Corpse ReviverNeg", new List<string> { "" }},

                { "Rum Old FashionedPos", new List<string> { "" }},
                { "Rum Old FashionedNeu", new List<string> { "" }},
                { "Rum Old FashionedNeg", new List<string> { "" }},

                { "PenicillinPos", new List<string> { "" }},
                { "PenicillinNeu", new List<string> { "" }},
                { "PenicillinNeg", new List<string> { "" }},

                { "Bloody MaryPos", new List<string> { "" }},
                { "Bloody MaryNeu", new List<string> { "" }},
                { "Bloody MaryNeg", new List<string> { "" }},

                { "MojitoPos", new List<string> { "" }},
                { "MojitoNeu", new List<string> { "" }},
                { "MojitoNeg", new List<string> { "" }},

                { "SazeracPos", new List<string> { "" }},
                { "SazeracNeu", new List<string> { "" }},
                { "SazeracNeg", new List<string> { "" }},

                { "Moscow MulePos", new List<string> { "" }},
                { "Moscow MuleNeu", new List<string> { "" }},
                { "Moscow MuleNeg", new List<string> { "" }},

                { "Aperol SpritzPos", new List<string> { "" }},
                { "Aperol SpritzNeu", new List<string> { "" }},
                { "Aperol SpritzNeg", new List<string> { "" }},

                { "MargaritaPos", new List<string> { "" }},
                { "MargaritaNeu", new List<string> { "" }},
                { "MargaritaNeg", new List<string> { "" }},

                { "ManhattanPos", new List<string> { "" }},
                { "ManhattanNeu", new List<string> { "" }},
                { "ManhattanNeg", new List<string> { "" }},

                { "DaiquiriPos", new List<string> { "" }},
                { "DaiquiriNeu", new List<string> { "" }},
                { "DaiquiriNeg", new List<string> { "" }},

                { "Whiskey SourPos", new List<string> { "" }},
                { "Whiskey SourNeu", new List<string> { "" }},
                { "Whiskey SourNeg", new List<string> { "" }},

                { "NegroniPos", new List<string> { "" }},
                { "NegroniNeu", new List<string> { "" }},
                { "NegroniNeg", new List<string> { "" }},

                { "Old FashionedPos", new List<string> { "" }},
                { "Old FashionedNeu", new List<string> { "" }},
                { "Old FashionedNeg", new List<string> { "" }},

                { "Dry MartiniPos", new List<string> { "" }},
                { "Dry MartiniNeu", new List<string> { "" }},
                { "Dry MartiniNeg", new List<string> { "" }},

                { "Spicy RyePos", new List<string> {""}},
                { "Spicy RyeNeu", new List<string> {""}},
                { "Spicy RyeNeg", new List<string> {""}},

                { "AperolPos", new List<string> {""}},
                { "AperolNeu", new List<string> {""}},
                { "AperolNeg", new List<string> {""}},

                { "Orange liqueurPos", new List<string> {""}},
                { "Orange liqueurNeu", new List<string> {""}},
                { "Orange liqueurNeg", new List<string> {""}},

                { "ScotchPos", new List<string> {""}},
                { "ScotchNeu", new List<string> {""}},
                { "ScotchNeg", new List<string> {""}},

                { "Smoky Islay ScotchPos", new List<string> {""}},
                { "Smoky Islay ScotchNeu", new List<string> {""}},
                { "Smoky Islay ScotchNeg", new List<string> {""}},

                { "Ginger BeerPos", new List<string> {""}},
                { "Ginger BeerNeu", new List<string> {""}},
                { "Ginger BeerNeg", new List<string> {""}},

                { "Lillet BlancPos", new List<string> {""}},
                { "Lillet BlancNeu", new List<string> {""}},
                { "Lillet BlancNeg", new List<string> {""}},

                { "AbsinthePos", new List<string> {""}},
                { "AbsintheNeu", new List<string> {""}},
                { "AbsintheNeg", new List<string> {""}},

                { "CombierPos", new List<string> {""}},
                { "CombierNeu", new List<string> {""}},
                { "CombierNeg", new List<string> {""}},

                { "TequilaPos", new List<string> {""}},
                { "TequilaNeu", new List<string> {""}},
                { "TequilaNeg", new List<string> {""}},

                { "MezcalPos", new List<string> {""}},
                { "MezcalNeu", new List<string> {""}},
                { "MezcalNeg", new List<string> {""}},

                { "BenedictinePos", new List<string> {""}},
                { "BenedictineNeu", new List<string> {""}},
                { "BenedictineNeg", new List<string> {""}},

                { "Maraschino LiqueurPos", new List<string> {""}},
                { "Maraschino LiqueurNeu", new List<string> {""}},
                { "Maraschino LiqueurNeg", new List<string> {""}},

                { "VermouthPos", new List<string> {""}},
                { "VermouthNeu", new List<string> {""}},
                { "VermouthNeg", new List<string> {""}},

                { "CachaçaPos", new List<string> {""}},
                { "CachaçaNeu", new List<string> {""}},
                { "CachaçaNeg", new List<string> {""}},

                { "Pusser’s Navy RumPos", new List<string> {""}},
                { "Pusser’s Navy RumNeu", new List<string> {""}},
                { "Pusser’s Navy RumNeg", new List<string> {""}},

                { "Dry VermouthPos", new List<string> {""}},
                { "Dry VermouthNeu", new List<string> {""}},
                { "Dry VermouthNeg", new List<string> {""}},

                { "Sweet VermouthPos", new List<string> {""}},
                { "Sweet VermouthNeu", new List<string> {""}},
                { "Sweet VermouthNeg", new List<string> {""}},

                { "Sparkling WinePos", new List<string> {""}},
                { "Sparkling WineNeu", new List<string> {""}},
                { "Sparkling WineNeg", new List<string> {""}},

                { "Italian VermouthPos", new List<string> {""}},
                { "Italian VermouthNeu", new List<string> {""}},
                { "Italian VermouthNeg", new List<string> {""}},

                { "Fernet-BrancaPos", new List<string> {""}},
                { "Fernet-BrancaNeu", new List<string> {""}},
                { "Fernet-BrancaNeg", new List<string> {""}},

                { "CampariPos", new List<string> {""}},
                { "CampariNeu", new List<string> {""}},
                { "CampariNeg", new List<string> {""}},

                { "CointreauPos", new List<string> {""}},
                { "CointreauNeu", new List<string> {""}},
                { "CointreauNeg", new List<string> {""}},

                { "WhiskeyPos", new List<string> {""}},
                { "WhiskeyNeu", new List<string> {""}},
                { "WhiskeyNeg", new List<string> {""}},

                { "SherryPos", new List<string> {""}},
                { "SherryNeu", new List<string> {""}},
                { "SherryNeg", new List<string> {""}},

                { "GinPos", new List<string> {""}},
                { "GinNeu", new List<string> {""}},
                { "GinNeg", new List<string> {""}},

                { "RumPos", new List<string> {""}},
                { "RumNeu", new List<string> {""}},
                { "RumNeg", new List<string> {""}},

                { "Triple SecPos", new List<string> {""}},
                { "Triple SecNeu", new List<string> {""}},
                { "Triple SecNeg", new List<string> {""}},

                { "Lillet VermouthPos", new List<string> {""}},
                { "Lillet VermouthNeu", new List<string> {""}},
                { "Lillet VermouthNeg", new List<string> {""}},

                { "ProseccoPos", new List<string> {""}},
                { "ProseccoNeu", new List<string> {""}},
                { "ProseccoNeg", new List<string> {""}},

                { "BrandyPos", new List<string> {""}},
                { "BrandyNeu", new List<string> {""}},
                { "BrandyNeg", new List<string> {""}},

                { "CognacPos", new List<string> {""}},
                { "CognacNeu", new List<string> {""}},
                { "CognacNeg", new List<string> {""}},

                { "ChampagnePos", new List<string> {""}},
                { "ChampagneNeu", new List<string> {""}},
                { "ChampagneNeg", new List<string> {""}},

                { "AmaroPos", new List<string> {""}},
                { "AmaroNeu", new List<string> {""}},
                { "AmaroNeg", new List<string> {""}},

                { "Rye WhiskeyPos", new List<string> {""}},
                { "Rye WhiskeyNeu", new List<string> {""}},
                { "Rye WhiskeyNeg", new List<string> {""}},

                { "Gosling’s RumPos", new List<string> {""}},
                { "Gosling’s RumNeu", new List<string> {""}},
                { "Gosling’s RumNeg", new List<string> {""}},

                { "White RumPos", new List<string> {""}},
                { "White RumNeu", new List<string> {""}},
                { "White RumNeg", new List<string> {""}},

                { "AmarettoPos", new List<string> {""}},
                { "AmarettoNeu", new List<string> {""}},
                { "AmarettoNeg", new List<string> {""}},

                { "PiscoPos", new List<string> {""}},
                { "PiscoNeu", new List<string> {""}},
                { "PiscoNeg", new List<string> {""}},

                { "Coca ColaPos", new List<string> { "Ice"}},
                { "Coca ColaNeu", new List<string> {
                    "Soda",
                    "Coconut cream",
                    "Syrup",
                    "Raspberry syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Sugar",
                    "Sweetener",
                    "Cane Sugar",
                    "Maraschino Cherries"}},
                { "Coca ColaNeg", new List<string> {
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Orange flower water",
                    "Cranberry juice",
                    "Tomato juice",
                    "Milk",
                    "Lemon",
                    "Lime",
                    "Egg",
                    "Orange",
                    "Mint",
                    "Peach puree",
                    "Cream",
                    "Heavy cream",
                    "Half and Half",
                    "Honey",
                    "Egg White",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Creme de Violette",
                    "Creme Yvette",
                    "Muddled mint",
                    "Spices",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Angostura Bitters"}},

                { "SodaPos", new List<string> {
                    "Raspberry syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Sugar",
                    "Mint",
                    "Orange bitters",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Sweetener",
                    "Cane Sugar",
                    "Muddled mint",
                    "Ice"}},
                { "SodaNeu", new List<string> {
                    "Coca Cola",
                    "Syrup",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Orange flower water",
                    "Cranberry juice",
                    "Angostura Bitters",
                    "Maraschino Cherries",
                    "Honey"}},
                { "SodaNeg", new List<string> {
                    "Coconut cream",
                    "Milk",
                    "Tomato juice",
                    "Egg",
                    "Peach puree",
                    "Cream",
                    "Egg White",
                    "Half and Half",
                    "Heavy cream",
                    "Peychauds bitters",
                    "Creme de Violette",
                    "Creme Yvette",
                    "Spices"} },

                { "Pineapple juicePos", new List<string> {
                    "Lemon juice",
                    "Orange juice",
                    "Lime juice",
                    "Syrup",
                    "Raspberry syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Soda",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Ice",
                    "Sugar",
                    "Orange bitters",
                    "Peach puree",
                    "Honey",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Sweetener",
                    "Cane Sugar"} },
                { "Pineapple juiceNeu", new List<string> {
                    "Orange flower water",
                    "Cranberry juice",
                    "Coconut cream",
                    "Angostura Bitters",
                    "Peychauds bitters"} },
                { "Pineapple juiceNeg", new List<string> {
                    "Coca Cola",
                    "Tomato juice",
                    "Milk",
                    "Egg",
                    "Mint",
                    "Cream",
                    "Heavy cream",
                    "Half and Half",
                    "Egg White",
                    "Creme de Violette",
                    "Creme Yvette",
                    "Spices",
                    "Maraschino Cherries",
                    "Muddled mint"} },

                { "Orange juicePos", new List<string> {
                    "Pineapple juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Raspberry syrup",
                    "Orange flower water",
                    "Lime juice",
                    "Lemon juice",
                    "Sweetener",
                    "Cane Sugar",
                    "Sugar",
                    "Orange",
                    "Spindrift grapefruit",
                    "Ice",
                    "Orange bitters"} },
                { "Orange juiceNeu", new List<string> {
                    "Soda",
                    "Cranberry juice",
                    "Lemon",
                    "Lime",
                    "Grapefruit",
                    "Angostura Bitters",
                    "Maraschino Cherries",
                    "Peychauds bitters"} },
                { "Orange juiceNeg", new List<string> {
                    "Coca Cola",
                    "Coconut cream",
                    "Tomato juice",
                    "Milk",
                    "Egg",
                    "Egg White",
                    "Honey",
                    "Mint",
                    "Peach puree",
                    "Cream",
                    "Half and Half",
                    "Heavy cream",
                    "Creme de Violette",
                    "Creme Yvette",
                    "Spices",
                    "Muddled mint"} },

                { "SyrupPos", new List<string> {
                    "Soda",
                    "Ice",
                    "Lemon",
                    "Lime",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Orange flower water",
                    "Cranberry juice",
                    "Raspberry syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Mint",
                    "Angostura Bitters",
                    "Maraschino Cherries",
                    "Orange bitters",
                    "Orange",
                    "Peach puree",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Peychauds bitters",
                    "Muddled mint"} },
                { "SyrupNeu", new List<string> {
                    "Coca Cola",
                    "Sugar",
                    "Honey",
                    "Sweetener",
                    "Cane Sugar"} },
                { "SyrupNeg", new List<string> {
                    "Coconut cream",
                    "Tomato juice",
                    "Milk",
                    "Spices",
                    "Egg White",
                    "Egg"} },

                { "Lemon juicePos", new List<string> {
                    "Lemon",
                    "Soda",
                    "Pineapple juice",
                    "Orange juice",
                    "Syrup",
                    "Lime juice",
                    "Cranberry juice",
                    "Raspberry syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Lime",
                    "Orange",
                    "Ice",
                    "Sugar",
                    "Sweetener",
                    "Cane Sugar"} },
                { "Lemon juiceNeu", new List<string> {

                    "Orange flower water",
                    "Angostura Bitters",
                    "Maraschino Cherries",
                    "Orange bitters",
                    "Honey",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Peychauds bitters"} },
                { "Lemon juiceNeg", new List<string> {
                    "Coca Cola",
                    "Coconut cream",
                    "Tomato juice",
                    "Milk",
                    "Mint",
                    "Peach puree",
                    "Egg White",
                    "Egg",
                    "Spices",
                    "Muddled mint"} },

                { "Lime juicePos", new List<string> {
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Ice",
                    "Soda",
                    "Sugar ",
                    "Cane Sugar",
                    "Sweetener"} },
                { "Lime juiceNeu", new List<string> {
                    "Honey"} },
                { "Lime juiceNeg", new List<string> {
                    "Maraschino Cherries",
                    "Peach puree",
                    "Coca Cola",
                    "Mint ",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters ",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Coconut cream",
                    "Egg"} },

                { "Orange flower waterPos", new List<string> {
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Ice",
                    "Soda",
                    "Sugar ",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters "} },
                { "Orange flower waterNeu", new List<string> {""} },
                { "Orange flower waterNeg", new List<string> {
                    "Maraschino Cherries",
                    "Peach puree",
                    "Coca Cola",
                    "Mint ",
                    "Muddled mint",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "Cranberry juicePos", new List<string> {
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Ice",
                    "Pineapple juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Soda",
                    "Sugar ",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },
                { "Cranberry juiceNeu", new List<string> {
                    "Maraschino Cherries",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Orange",
                    "Lime",
                    "Lemon",
                    "Peach puree",
                    "Lemon juice",
                    "Orange juice",
                    "Lime juice",
                    "Orange flower water"} },
                { "Cranberry juiceNeg", new List<string> {
                    "Coca Cola",
                    "Mint ",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters ",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "Raspberry syrupPos", new List<string> {
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Ice","Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },
                { "Raspberry syrupNeu", new List<string> {
                    "Orange flower water",
                    "Syrup",
                    "Ginger Syrup",
                    "Demerara syrup",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree"} },
                { "Raspberry syrupNeg", new List<string> {
                    "Mint",
                    "Muddled mint",
                    "Coca Cola",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "Ginger SyrupPos", new List<string> {
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Ice",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Orange flower water",
                    "Syrup",
                    "Demerara syrup",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "Ginger SyrupNeu", new List<string> {
                    "Mint",
                    "Muddled mint",
                    "Coca Cola"} },
                { "Ginger SyrupNeg", new List<string> {
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "Tomato juicePos", new List<string> {
                    "Ice",
                    "Spices"} },
                { "Tomato juiceNeu", new List<string> {
                    "Egg",
                    "Cream"} },
                { "Tomato juiceNeg", new List<string> {
                    "Milk ",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Coca Cola",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Mint",
                    "Muddled mint"} },

                { "Demerara syrupPos", new List<string> {
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Orange flower water",
                    "Ice",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                     "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                     "Soda"} },
                { "Demerara syrupNeu", new List<string> {
                    "Peach puree",
                     "Coca Cola",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "Demerara syrupNeg", new List<string> {
                    "Mint",
                    "Muddled mint",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "MilkPos", new List<string> {""} },
                { "MilkNeu", new List<string> {
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Ice",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Cream"} },
                { "MilkNeg", new List<string> {
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Orange flower water",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Coca Cola",
                    "Soda",
                    "Mint",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Tomato juice",
                    "Spices",
                    "Egg"} },

                { "Red-bullPos", new List<string> {
                    "Ice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Coca Cola",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },
                { "Red-bullNeu", new List<string> {
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Mint",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "Red-bullNeg", new List<string> {
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "IcePos", new List<string> {
                    "Coca Cola",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Mint",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },
                { "IceNeu", new List<string> {""} },
                { "IceNeg", new List<string> {""} },

                { "SugarPos", new List<string> {
                    "Ice",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Coca Cola",
                    "Soda",
                    "Mint",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters",
                    "Milk ",
                    "Cream"} },
                { "SugarNeu", new List<string> {
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },
                { "SugarNeg", new List<string> {
                    "Tomato juice",
                    "Spices",
                    "Egg"} },

                { "EggPos", new List<string> {
                    "Ice",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream"} },
                { "EggNeu", new List<string> {
                    "Syrup",
                    "Sugar",
                    "Sweetener"} },
                { "EggNeg", new List<string> {
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Coca Cola",
                    "Soda",
                    "Cane Sugar",
                    "Honey",
                    "Mint",
                    "Muddled mint",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },

                { "OrangePos", new List<string> {
                    "Ice",
                    "Lemon",
                    "Lime",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },

             { "OrangeNeu", new List<string> {
                       "Maraschino Cherries",
                    "Peach puree",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "OrangeNeg", new List<string> {
                    "Mint",
                    "Muddled mint",
                    "Coca Cola",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },

                { "LemonPos", new List<string> {
                    "Ice",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Maraschino Cherries",
                    "Peach puree",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Orange flower water",
                    "Coca Cola",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener"} },
                { "LemonNeu", new List<string> {
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "LemonNeg", new List<string> {
                    "Mint",
                    "Muddled mint",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"} },
                { "LimePos", new List<string> {
                    "Ice",
                    "Lemon",
                    "Lime",
                    "Orange",
                    "Grapefruit",
                    "Spindrift grapefruit",
                    "Pineapple juice",
                    "Orange juice",
                    "Lemon juice",
                    "Lime juice",
                    "Cranberry juice",
                    "Syrup",
                    "Ginger Syrup",
                    "Raspberry syrup",
                    "Demerara syrup",
                    "Soda",
                    "Sugar",
                    "Cane Sugar",
                    "Honey",
                    "Sweetener",
                    "Orange flower water"} },
                { "LimeNeu", new List<string> {
                    "Coca Cola",
                    "Angostura Bitters",
                    "Peychauds bitters",
                    "Orange bitters"} },
                { "LimeNeg", new List<string> {
                    "Maraschino Cherries",
                    "Peach puree",
                    "Mint",
                    "Muddled mint",
                    "Tomato juice",
                    "Spices",
                    "Milk ",
                    "Cream",
                    "Egg"}}};
        public static void SaveCocktailsDB()
        {        List<string> cocktail = new List<string> {
                "White Russian,Vodka,Heavy cream (half and half),Coffee liqueur",
                "Black Russian,Vodka,Coffee liqueur",
                "Bellini,Prosecco,Peach puree",
                "Champagne Cocktail,Brandy (Cognac),Champagne,Angostura Bitters,Sugar cube",
                "Irish Coffee,Whiskey,Cream,Sugar",
                "Bamboo,Sherry,Dry Vermouth,Angostura bitters,Orange bitters",
                "Long Island Iced Tea,Vodka,Gin,Tequila,Rum,Triple Sec,Coca Cola",
                "Vesper,Vodka,Gin,Lillet Vermouth",
                "Caipirinha,Cachaça,Sugar,Lime",
                "Tom Collins,Gin,Lemon,Soda",
                "Painkiller,Pusser’s Navy Rum,Coconut cream,Pineapple juice,Orange juice",
                "Bees Knees,Gin,Lemon,Honey",
                "Ramos Gin Fizz,Gin,Syrup,Lemon juice,Lime juice,Egg White,Heavy cream,Orange flower water",
                "Bramble,Gin,Lemon,Syrup,Ice",
                "Vodka Martini,Vodka, Dry Vermouth",
                "Hanky Panky,Gin,Italian Vermouth,Fernet-Branca",
                "Jungle Bird,Rum,Campari,Lime,Pineapple juice,Sugar",
                "White Lady,Gin,Lemon juice,Cointreau (Combier)",
                "Paloma,Tequila (Mezcal),Grapefruit,Spindrift grapefruit Soda,Lime juice",
                "Cosmopolitan,Vodka,Triple sec,Cranberry juice,Lime juice",
                "Sidecar,Brandy,Lemon,Triple sec",
                "French 75,Gin,Lemon juice,Sugar,Champagne",
                "Vieux Carré,Brandy,Whiskey,Sweet Vermouth,Benedictine,Angostura Bitters,Peychauds bitters",
                "Aviation,Crème de Violette (Creme Yvette),Maraschino Liqueur,Gin,Lemon juice",
                "Piña Colada,White Rum,Coconut cream,and Pineapple juice",
                "Amaretto Sour,Amaretto,Lemon juice,Egg White",
                "Pisco Sour,Pisco,Lime,Syrup,Egg White",
                "Americano,Campari,Vermouth,Soda",
                "Gimlet,Gin,Lime juice,Sweetener",
                "Mai Tai,Rum,Orange juice,Triple sec,Sweetener",
                "Boulevardier,Rye Whiskey,Amaro,Sweet Vermouth",
                "Clover Club,Gin,Lemon juice,Raspberry syrup,Egg White",
                "Gin Fizz,Gin,Lemon,Sugar,Egg,Soda",
                "Dark ’N’ Stormy,Gosling’s Rum,Ginger Beer",
                "Corpse Reviver,Gin,Lemon juice,Cointreau,Lillet Blanc,Absinthe",
                "Rum Old Fashioned,Rum,Coca Cola",
                "Penicillin,Scotch,Smoky Islay Scotch,Lemon juice,Honey Ginger Syrup",
                "Bloody Mary,Vodka,Tomato juice,Spices",
                "Mojito,White Rum,Lime juice,Cane Sugar,Soda,Muddled mint",
                "Sazerac,Rye Whiskey (Brandy),Demerara syrup,Peychaud’s Bitters,Absinthe",
                "Moscow Mule,Ginger,Vodka,Lime,Soda",
                "Aperol Spritz,Prosecco,Aperol,Soda",
                "Margarita,Tequila,Orange liqueur,Lime juice",
                "Dry Martini,Gin,Dry Martini",
                "Manhattan,Spicy Rye,Sweet Vermouth,Angostura bitters",
                "Daiquiri,White Rum,Lime juiceSyrup",
                "Whiskey Sour,Whiskey,Lemon juice,Sugar,Egg White",
                "Negroni,Gin,Campari,Vermouth",
                "Old Fashioned,Rye Whiskey (Bourbon),Sugar cube,Angostura bitters,Ice" };
        List<string> components = new List<string>(); components.Clear();
            Dictionary<string, List<string>> CocktailsGeneral = new Dictionary<string, List<string>>();
            for (int i = 0; i < cocktail.Count(); i++)
            {
                components.Clear();
                string[] splitted = cocktail[i].Split(',');
                for (int j = 1; j < splitted.Count(); j++)
                {
                    if (splitted[j] != "" && splitted[j] != " " && splitted[j] != "\n" && splitted[j] != null) { components.Add(splitted[j]); }
                }
                CocktailsGeneral[splitted[0]] = new List<string>(components);
            }
            SaveDic(CocktailsGeneral, "CocktailsGeneral");
        }
        public static void SaveDic(Dictionary<string, List<string>> dic, string name)
        {
            if (!Directory.Exists(@"DataBank")) { Directory.CreateDirectory(@"DataBank"); }
            string pfad = @"DataBank\" + name + ".bin";
            var binaryFormatter = new BinaryFormatter(); var fi = new FileInfo(pfad);
            using (var binaryFile = fi.Create())
            { binaryFormatter.Serialize(binaryFile, dic); binaryFile.Flush(); }
        }
    }
}
/*#######################################################Resources#################################################################
Drinks
Dictionary: Dictionary<string, List<string>> ["Cocktail"](list of components)
File: MixComponents.bin, List<List<string>> (List<string> Alcoholic, List<string> Nonalcoholic,List<string> NonDrink)
File: Compatibility.bin, Dictionary<string, List<string>> ["DrinkPos"](list of matches),List<string>> ["DrinkNeu"](list of neutral),List<string>> ["DrinkNeg"](list of mismatches) 

Cocktails
Dictionaries: Dictionary<string, List<string>> ComponentsPriv, Dictionary<string, List<string>> ComponentsGen
File: CocktailsGeneral.bin: Dictionary<string, List<string>>
File: CocktailsPrivate.bin: Dictionary<string, List<string>>*/
